language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.10.1
  - DJANGO=1.9.9
  - DJANGO=1.8.14
install:
  - pip install -q Django==$DJANGO
  - pip install -q flake8
  - pip install -q -e .
script:
  - PYFLAKES_NODOCTEST=1 flake8 logan
  - python setup.py test
